GET http://localhost/laxman


###   


GET http://localhost/user/users

###   
GET http://localhost/user/user/lakshmana5296@gmail.com
 

###   
GET http://localhost/user/user/email/lakshmana5296@gmail.com/username/laxman
###

POST http://localhost/user/create-user
Content-Type: application/json

{
    "username":"S170116",
    "email":"s170116@gmail.com",
    "age":20
}

###

POST http://localhost/user/create-user
Content-Type: application/json

{
    "username":"S170113",
    "email":"s170113@gmail.com",
    "age":20
}

###   



PUT http://localhost/user/modify-user
Content-Type: application/json

{
    "username":"laxmana rao",
    "email":"lakshmana5296@gmail.com",
    "age":20
}


###

DELETE http://localhost/user/delete/s170116@gmail.com

###







# Working on Products

###

#get all products
GET http://localhost/stopServer
###

#get all products
GET http://localhost/products/products


###
#get products by product id
GET http://localhost/products/product/2


###

# Add products
POST http://localhost/products/addProduct
Content-Type: application/json

{
        "productId":3,
        "productName":"Iphone 14",
        "brand":"Apple"
}

###

#modify product
PUT http://localhost/products/modify-product
Content-Type: application/json

{
    "productId":1,
    "productName":"Galaxy s23 ultra",
    "brand":"Samsung"
}

###

#Delete product by id
DELETE http://localhost/products/delete/2