GET http://localhost/laxman


###   


GET http://localhost/user/users

###   
GET http://localhost/user/user/580
 

###   
GET http://localhost/user/user/email/lakshmana5296@gmail.com/username/laxman
###

POST http://localhost/user/create-user
Content-Type: application/json

{
    "emp_id":"511",
    "emp_name":"deepthi",
    "emp_city":"Hyd",
    "emp_designation":"Associate software developer",
    "emp_age":21
}

###

POST http://localhost/user/create-user
Content-Type: application/json

{
    "emp_id":"512",
    "emp_name":"laxmana rao",
    "emp_city":"Hyd",
    "emp_designation":"Associate software developer",
    "emp_age":20
}

###   



PUT http://localhost/user/modify-user
Content-Type: application/json

{
    "emp_id":"512",
    "emp_name":"Boddepalli laxmana rao",
    "emp_city":"Hyd",
    "emp_designation":"Associate software developer",
    "emp_age":20
}


###

DELETE http://localhost/user/delete/512

###







# Working on Products

###

#get all products
GET http://localhost/stopServer
###

#get all products
GET http://localhost/products/products


###
#get products by product id
GET http://localhost/products/product/3


###

# Add products
POST http://localhost/products/addProduct
Content-Type: application/json

{
        "productId":3,
        "productName":"Iphone 14",
        "brand":"Apple"
}

###
# Add products
POST http://localhost/products/addProduct
Content-Type: application/json

{
        "productId":4,
        "productName":"Samsung galaxy s23",
        "brand":"samsung"
}

###

#modify product
PUT http://localhost/products/modify-product
Content-Type: application/json

{
    "productId":4,
    "productName":"Galaxy s23 ultra",
    "brand":"Samsung"
}

###

#Delete product by id
DELETE http://localhost/products/delete/3